language: node_js
node_js:
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
after_success:
  - ./scripts/deploy.sh
cache:
  directories:
    - node_modules
    - client/bower_components
services: mongodb
